version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/server/node_modules

  client:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - server
    volumes:
      - ./client:/app
