services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules  # Fixed: removed 'server' from path

  client:
    build:
      context: .  # Build context is project root
      dockerfile: client/Dockerfile  # Dockerfile path relative to context
    ports:
      - "3000:5173"  # Fixed: Map to port 5173 (Vite's default)
    env_file:
      - ./client/.env
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules  # Add this to preserve node_modules
